name = "saitamau-maximum-auth"
pages_build_output_dir = "build/client"
compatibility_date = "2024-09-02"

[vars]
GITHUB_APP_ID = "387915"
GITHUB_OAUTH_ID = "Iv1.3fef0e17322d38ce"

[env.production]
compatibility_date = "2024-09-02"

[env.production.vars]
CF_PAGES_URL = "https://auth.maximum.vc"
GITHUB_APP_ID = "387915"
GITHUB_OAUTH_ID = "Iv1.3fef0e17322d38ce"
