name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saitamau-maximum'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        working-directory: package

      - name: Test
        run: pnpm test
        working-directory: package

      - name: Build Test
        run: pnpm build
        working-directory: package

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saitamau-maximum'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        working-directory: package

      - name: Build
        run: pnpm build
        working-directory: package

      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
