name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install
        working-directory: ./package

      - name: Build Test
        run: pnpm build
        working-directory: ./package

      - name: Test
        run: pnpm test
        working-directory: ./package

  webapp:
    name: Webapp
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps for package
        run: pnpm install
        working-directory: ./package

      - name: Build package
        run: pnpm build
        working-directory: ./package

      - name: Install deps
        run: pnpm install
        working-directory: ./webapp

      - name: Build Test
        run: pnpm build
        working-directory: ./webapp

      - name: Test
        run: pnpm test
        working-directory: ./webapp

  worker:
    name: Worker
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps for package
        run: pnpm install
        working-directory: ./package

      - name: Build package
        run: pnpm build
        working-directory: ./package

      - name: Install deps
        run: pnpm install
        working-directory: ./worker

      - name: Test
        run: pnpm test
        working-directory: ./worker
